  HttpProxyClientSocketPoolSpdy3Test()
      : session_deps_(kProtoSPDY3),
        ssl_config_(),
        ignored_transport_socket_params_(
            new TransportSocketParams(HostPortPair("proxy", 80),
                                      LOWEST,
                                      false,
                                      false,
                                      OnHostResolutionCallback())),
        ignored_ssl_socket_params_(
            new SSLSocketParams(ignored_transport_socket_params_,
                                NULL,
                                NULL,
                                ProxyServer::SCHEME_DIRECT,
                                HostPortPair("www.google.com", 443),
                                ssl_config_,
                                0,
                                false,
                                false)),
        tcp_histograms_("MockTCP"),
        transport_socket_pool_(
            kMaxSockets,
            kMaxSocketsPerGroup,
            &tcp_histograms_,
            session_deps_.deterministic_socket_factory.get()),
        ssl_histograms_("MockSSL"),
        ssl_socket_pool_(kMaxSockets,
                         kMaxSocketsPerGroup,
                         &ssl_histograms_,
                         session_deps_.host_resolver.get(),
                         session_deps_.cert_verifier.get(),
                         NULL /* server_bound_cert_store */,
                         NULL /* transport_security_state */,
                         std::string() /* ssl_session_cache_shard */,
                         session_deps_.deterministic_socket_factory.get(),
                         &transport_socket_pool_,
                         NULL,
                         NULL,
                         session_deps_.ssl_config_service.get(),
                         BoundNetLog().net_log()),
        session_(CreateNetworkSession()),
        http_proxy_histograms_("HttpProxyUnitTest"),
        spdy_util_(kProtoSPDY3),
        ssl_data_(NULL),
        data_(NULL),
        pool_(kMaxSockets,
              kMaxSocketsPerGroup,
              &http_proxy_histograms_,
              NULL,
              &transport_socket_pool_,
              &ssl_socket_pool_,
              NULL) {
  }
